package employee.web.actions;

import com.ctc.wstx.dtd.PrefixedNameSet;
import com.liferay.counter.kernel.service.CounterLocalService;
import com.liferay.oauth2.provider.scope.spi.prefix.handler.PrefixHandlerFactory;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.Company;
import com.liferay.portal.kernel.model.Contact;
import com.liferay.portal.kernel.model.Group;
import com.liferay.portal.kernel.model.GroupConstants;
import com.liferay.portal.kernel.model.Role;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.UserConstants;
import com.liferay.portal.kernel.model.UserModel;
import com.liferay.portal.kernel.model.role.RoleConstants;
import com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand;
import com.liferay.portal.kernel.portlet.bridges.mvc.MVCActionCommand;
import com.liferay.portal.kernel.service.CompanyLocalService;
import com.liferay.portal.kernel.service.ContactLocalService;
import com.liferay.portal.kernel.service.GroupLocalService;
import com.liferay.portal.kernel.service.RoleLocalService;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.ServiceContextFactory;
import com.liferay.portal.kernel.service.UserLocalService;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.theme.ThemeDisplay;
import com.liferay.portal.kernel.util.ParamUtil;
import com.liferay.portal.kernel.util.WebKeys;

import java.util.Calendar;
import java.util.Date;
import java.util.Locale;

import javax.portlet.ActionRequest;
import javax.portlet.ActionResponse;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

import employee.service.model.Employee;
import employee.service.service.EmployeeLocalService;
import employee.web.constants.EmployeeWebPortletKeys;

@Component(property = { "javax.portlet.name=" + EmployeeWebPortletKeys.EMPLOYEEWEB,
		"mvc.command.name=addEmployee" }, service = MVCActionCommand.class)

public class AddEmployeeMVCAction extends BaseMVCActionCommand {

	@Override
	protected void doProcessAction(ActionRequest actionRequest, ActionResponse actionResponse) throws PortalException {

		String firstName = ParamUtil.getString(actionRequest, "firstName");
		String lastName = ParamUtil.getString(actionRequest, "lastName");
		String emailAddress = ParamUtil.getString(actionRequest, "emailAddress");
		String password = ParamUtil.getString(actionRequest, "password");
		String phoneNumber = ParamUtil.getString(actionRequest, "phoneNumber");
		String addressLine1 = ParamUtil.getString(actionRequest, "addressLine1");
		String addressLine2 = ParamUtil.getString(actionRequest, "addressLine2");
		String city = ParamUtil.getString(actionRequest, "city");
		String zipCode = ParamUtil.getString(actionRequest, "zipCode");
		String designation = ParamUtil.getString(actionRequest, "designation");

		ThemeDisplay themeDisplay = (ThemeDisplay) actionRequest.getAttribute(WebKeys.THEME_DISPLAY);
		long groupId = themeDisplay.getCompanyGroupId();
		long currentUserId = themeDisplay.getUserId();
		long companyId = themeDisplay.getCompanyId();

		// first check if email already exits or not in the system
		// create a user id using counterlocalservcie
		// userLocalService.createUser(0);
		// set the parameters for the user object
		
		
	try {

		
		//System.out.println("UserId generated by counterLocalServcie for new user : " + creatorUserId);
		
//		long contactUserId = counterLocalService.increment(Contact.class.getName());
//
//		Contact contact  = contactLocalService.createContact(creatorUserId);

		Locale locale = null;

		locale = locale.US;

		boolean autoPassword = false;
		
		//boolean passwordReset = false; // true
		

		boolean autoScreenName = false;

		String screenName = firstName + "_" + lastName;
		String middleName = "";
		
		
		

		long prefixListTypeId = 0;
		long suffixListTypeId = 0;
		boolean male = false;
		
		
		Calendar calender = Calendar.getInstance();
		
	
		int birthdayMonth = calender.JANUARY;
		int birthdayDay = 1;
		int birthdayYear = 1970;
		
		
		String jobTitle = designation;

		Group guestGroup = _groupLocalService.getGroup(companyId, GroupConstants.GUEST);

		long[] groupIds = { guestGroup.getGroupId() };

		long[] organizationIds = null;

		Role userRole = _roleLocalService.getRole(companyId, RoleConstants.USER);

		long[] roleIds = { userRole.getRoleId() };

		long[] userGroupIds = null;

		boolean sendEmail = false;

		//ServiceContext serviceContext = new ServiceContext();
		
		ServiceContext serviceContext = ServiceContextFactory.getInstance(User.class.getName(), actionRequest);

		System.out.println("Gusest Group Id : " + guestGroup.getGroupId());
		
		System.out.println("Company id : " + companyId);
		
		System.out.println("Before Add User Method");
				
		User user =   userLocalService.addUser(currentUserId,companyId, autoPassword, password, password, 
				autoScreenName, screenName, emailAddress, locale, firstName, middleName, lastName, 
				prefixListTypeId, suffixListTypeId, male, 
				birthdayMonth,birthdayDay, birthdayYear,jobTitle, UserConstants.TYPE_REGULAR, groupIds, organizationIds, roleIds, userGroupIds, sendEmail, serviceContext);
		
		
	System.out.println("Successfuly new user added ");
	
	System.out.println("User Id of newly created user: " + user.getUserId());

	

		long employeeId = counterLocalService.increment(Employee.class.getName());

		Employee employee = employeeLocalServcice.createEmployee(employeeId);
		
		
		employee.setUserId(currentUserId); //audit filed
		
		employee.setUserName(screenName);
		
		employee.setGroupId(groupId);

		employee.setFirstName(firstName);

		employee.setLastName(lastName);

		employee.setPassword(password);

		employee.setEmailAddress(emailAddress);

		employee.setPhoneNumber(phoneNumber);

		employee.setAddressLine1(addressLine1);

		employee.setAddressLine2(addressLine2);

		employee.setCity(city);

		employee.setZipCode(zipCode);

		employee.setDesignation(designation);
		
		employeeLocalServcice.addEmployee(employee);
		
		System.out.println("Employee created successfully");
		
		
	}catch(Exception e) {
		System.out.println("Exception in Add Employee with user method" + e);
	}
	
		

	}

	@Reference
	private CounterLocalService counterLocalService;

	@Reference
	private EmployeeLocalService employeeLocalServcice;

	@Reference
	private UserLocalService userLocalService;

	@Reference
	private GroupLocalService _groupLocalService;

	@Reference
	private CompanyLocalService _companyLocalService;
	
	@Reference
	private ContactLocalService contactLocalService;

	@Reference
	private RoleLocalService _roleLocalService;
	
	

}
